kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ikaruswill/octopi-wp-php
    tags:
      - latest
      - ${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag
